spring:
  application:
    name: pd-test-backend
    
  datasource:
    # allowPublicKeyRetrieval=true 추가
    url: jdbc:mysql://52.79.176.109:3306/pd_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rootpassword1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  redis:
    host: 52.79.176.109
    port: 6379
    password: redispassword1234
    
server:
  port: 8080
  
logging:
  level:
    org.springframework.web: DEBUG
    com.test: DEBUG

# CORS 설정 (Frontend 접근 허용)
cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000
    - http://52.79.176.109
    - http://52.79.176.109:80
    - http://52.79.176.109:3000
