name: Backend Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy Backend to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Backend 업데이트
          cd ~/pd-test/backend
          git pull origin main
          
          # Docker 이미지 빌드
          docker build -t pd-test-backend:latest .
          
          # 서비스 재시작
          cd ~/pd-test
          docker-compose stop backend
          docker-compose rm -f backend
          docker-compose up -d backend
          
          # 오래된 이미지 정리
          docker image prune -f
          
          echo "Backend deployment completed!"
